version: 2.1

jobs:
  sast_semgrep:
    docker:
      - image: returntocorp/semgrep:latest
    steps:
      - checkout
      - run:
          name: Run Semgrep (SAST)
          command: |
            semgrep --version
            semgrep --config p/security-audit --error

  dast_trivy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t demo-sec:latest .
      - run:
          name: Trivy scan (DAST)
          command: |
            docker run --rm \
              aquasec/trivy:latest image \
              --severity HIGH,CRITICAL \
              --ignore-unfixed \
              --exit-code 1 \
              demo-sec:latest

workflows:
  security_pipeline:
    jobs:
      - sast_semgrep
      - dast_trivy:
          requires:
            - sast_semgrep