version: 2.1

jobs:
  sast_semgrep:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Semgrep
          command: |
            pip install --upgrade pip
            pip install semgrep
      - run:
          name: Run Semgrep (SAST)
          command: |
            semgrep --version
            semgrep scan --config p/security-audit --error .

  dast_trivy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build -t demo-sec:latest .

      - run:
          name: Install Trivy
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo "deb https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install -y trivy
            trivy --version

      - run:
          name: Trivy scan (DAST) - Secrets
          command: |
            trivy fs --scanners secret --exit-code 1 --format table .

workflows:
  security_pipeline:
    jobs:
      - sast_semgrep
      - dast_trivy:
          requires:
            - sast_semgrep
