apiVersion: v1
kind: Service
metadata:
  name: taller-app
  namespace: taller
  labels:
    app: taller-app
spec:
  selector:
    app: taller-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
